name: Clipy
options:
  developmentLanguage: ja
  xcodeVersion: 12.2
  deploymentTarget:
    iOS: 14.0.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 14.0.0
    TARGETED_DEVICE_FAMILY: 1,2
    SWIFT_VERSION: 5.0
config:
  Debug: debug
  Release: release
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.9.0
targets:
  Clipy:
    type: application
    platform: iOS
    developmentTarget: 14.0.0
    sources:
      - path: Clipy
    scheme: {}
    dependencies:
      - package: ComposableArchitecture
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1,2
        DEVELOPMENT_TEAM: AV9FQ3YF56
        PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.Clipy
        INFOPLIST_FILE: ./Clipy/Resources/Info.plist
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.tomoki-sun.app.ios.Clipy
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.tomoki-sun.app.ios.Clipy

  ClipyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ClipyTests
    dependencies:
      - target: Clipy
    scheme:
      gatherCoverageData: true
      testTargets:
        - ClipyTests